env:
  global:
  - NODE_VERSION=8.6.0
  - EMULATOR_API_LEVEL=24
  - ANDROID_VERSION=24
  - ANDROID_BUILD_TOOLS_VERSION=26.0.1
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
  - APPIUM_VERSION=1.7.1
language: android
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_VERSION
  - android-$EMULATOR_API_LEVEL
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install:
- nvm install $NODE_VERSION
- npm install -g typings
- wget -O ./nativescript.tgz "https://s3.amazonaws.com/nativescript-ci/build_result/nativescript.tgz"
- npm install -g nativescript.tgz --ignore-scripts
- tns usage-reporting disable
- tns error-reporting disable
- npm install
- npm i appium@$APPIUM_VERSION
before_script:
  - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -memory 1024 -avd test -no-audio -no-window -engine classic &
  - android-wait-for-emulator
script:
- tns build android
- android-wait-for-emulator
- npm run test